version: '3'
services:
  yeehack:
    build:
      context: https://github.com/aso824/yeehack.git
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    volumes:
      - '/var/run/dbus:/run/dbus:ro'
