version: '3'
services:
  yeehack:
    build:
      context: https://github.com/aso824/yeehack.git
      dockerfile: Dockerfile
    volumes:
      - /var/run/dbus:/run/dbus:ro
    network_mode: host
    restart: unless-stopped
